spring.application.name=demo
logging.level.com.RESTfull_API_CRUD_Example=TRACE
spring.datasource.url=jdbc:postgresql://postgres:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
