spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/user_api}
    username: ${DB_USERNAME:userapi}
    password: ${DB_PASSWORD:userapi}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: false

server:
  port: 8080
